name: pylint workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repositry"
        uses: actions/checkout@v4
      - name: "Install packages"
        run: pip install -r pipeline/requirements.txt
      - name: "lint code"
        run: pylint --fail-under=7 pipeline/pipeline_realtime.py