name: pylint/pytest workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repositry"
        uses: actions/checkout@v4
      - name: "Install pylint"
        run: pip install pylint
      - name: "Install packages"
        run: pip install -r old_data/sensor_reading_to_s3/requirements.txt
      - name: "Install packages"
        run: pip install -r old_data/metadata_to_s3/requirements.txt
      - name: "Analysing the code with pylint"
        run: |
          pylint --fail-under 8 $(git ls-files '*.py')
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: "Checkout repositry"
        uses: actions/checkout@v4
      - name: "Install packages"
        run: pip install -r pipeline/requirements.txt
      - name: "Install packages"
        run: pip install -r old_data/sensor_reading_to_s3/requirements.txt
      - name: "Install packages"
        run: pip install -r old_data/metadata_to_s3/requirements.txt
      - name: "Run tests"
        run: pytest
